#!/usr/bin/env python3
"""Generate Postfix + Dovecot config from tenant JSON."""

import json
import os
import subprocess
import sys
from pathlib import Path

CONFIG_PATH = os.environ.get("CONFIG_PATH", "/config/tenant.json")
CERT_DIR = Path("/data/certs")


def load_config() -> dict:
    with open(CONFIG_PATH) as f:
        return json.load(f)


def generate_cert(hostname: str) -> None:
    CERT_DIR.mkdir(parents=True, exist_ok=True)
    cert, key = CERT_DIR / "smtp.crt", CERT_DIR / "smtp.key"
    if cert.exists() and key.exists():
        print(f"TLS cert exists for {hostname}")
        return
    print(f"Generating self-signed TLS cert for {hostname}...")
    subprocess.run([
        "openssl", "req", "-x509", "-nodes", "-newkey", "rsa:2048",
        "-keyout", str(key), "-out", str(cert), "-days", "3650",
        "-subj", f"/CN={hostname}/O=SMTP OAuth Proxy",
        "-addext", f"subjectAltName=DNS:{hostname},IP:127.0.0.1",
    ], check=True, capture_output=True)
    print(f"TLS cert generated: {cert}")


def write_dovecot_users(username: str, password: str) -> None:
    path = Path("/etc/dovecot/users")
    path.write_text(f"{username}:{{PLAIN}}{password}\n")
    path.chmod(0o644)  # Dovecot runs as uid=101, needs read access
    print(f"Dovecot auth: user={username}")


def write_main_cf(config: dict) -> None:
    tls_mode = config.get("smtp_tls_mode", "starttls")
    hostname = config.get("smtp_hostname", "smtp.proxy.local")
    bf_max = config.get("bf_max_attempts", 5)
    bf_minutes = config.get("bf_lockout_minutes", 30)

    tls_level = {
        "starttls": "encrypt",       # STARTTLS required
        "starttls_optional": "may",  # STARTTLS offered, optional
        "tls": "encrypt",            # treat same as starttls (465 = future todo)
        "plain": "none",             # no TLS
    }.get(tls_mode, "may")

    # Ensure persistent queue directory exists
    Path("/data/spool").mkdir(parents=True, exist_ok=True)

    main_cf = f"""# Generated by oauth-multitenant-proxy configure.py
# Tenant: {config.get("tenant_name", "unknown")}
compatibility_level = 3.6
# Queue on persistent volume — survives container recreation
queue_directory = /data/spool
smtpd_banner = {hostname} ESMTP
myhostname = {hostname}
myorigin = $myhostname
inet_interfaces = all
inet_protocols = ipv4
mydestination =
mynetworks = 127.0.0.0/8
relayhost =

# TLS
smtpd_tls_cert_file = /data/certs/smtp.crt
smtpd_tls_key_file = /data/certs/smtp.key
smtpd_tls_security_level = {tls_level}
smtpd_tls_loglevel = 1
smtpd_tls_protocols = !SSLv2 !SSLv3 !TLSv1 !TLSv1.1
smtpd_tls_mandatory_protocols = !SSLv2 !SSLv3 !TLSv1 !TLSv1.1
smtpd_tls_received_header = yes

# SASL via Dovecot — supports any username format including user@domain
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
smtpd_sasl_security_options = noanonymous
broken_sasl_auth_clients = yes

# Only authenticated users may relay
smtpd_relay_restrictions = permit_sasl_authenticated, reject
smtpd_recipient_restrictions = permit_sasl_authenticated, reject

# Brute-force: max {bf_max} auth failures per {bf_minutes}min window
smtpd_client_auth_rate_limit = {bf_max}
anvil_rate_time_unit = {bf_minutes}m

# Route all outbound mail to our OAuth MDA
default_transport = oauth
transport_maps = hash:/etc/postfix/transport

# Limits
message_size_limit = 26214400
mailbox_size_limit = 0
local_transport = error:5.1.1 Local delivery disabled

# Log to stdout for Docker
maillog_file = /dev/stdout
"""
    Path("/etc/postfix/main.cf").write_text(main_cf)
    print(f"main.cf written (TLS: {tls_mode} → smtpd_tls_security_level={tls_level})")


def write_transport() -> None:
    t = Path("/etc/postfix/transport")
    t.write_text("* oauth:\n")
    subprocess.run(["postmap", str(t)], check=True)
    print("Transport map: all mail → oauth pipe")


def ensure_aliases() -> None:
    aliases = Path("/etc/aliases")
    if not aliases.exists():
        aliases.write_text("# generated\n")
    subprocess.run(["newaliases"], check=True, capture_output=True)


LOCAL_CONFIG = Path("/etc/oauth_proxy_config.json")


def copy_config_local(config_path: str) -> None:
    """Copy the tenant config to a fixed local path readable by Postfix pipe (nobody).
    Postfix pipe transport does not inherit container environment variables,
    so we cannot rely on CONFIG_PATH being available to oauth_deliver.py."""
    import shutil
    shutil.copy(config_path, LOCAL_CONFIG)
    LOCAL_CONFIG.chmod(0o644)
    print(f"Config copied to {LOCAL_CONFIG} (readable by nobody/Postfix pipe)")


def main() -> None:
    config = load_config()
    tenant = config.get("tenant_name", "unknown")
    hostname = config.get("smtp_hostname", "smtp.proxy.local")
    oauth_count = len(config.get("oauth_configs", []))

    print(f"Tenant:       {tenant}")
    print(f"Hostname:     {hostname}")
    print(f"TLS mode:     {config.get('smtp_tls_mode', 'starttls')}")
    print(f"OAuth configs:{oauth_count}")

    if oauth_count == 0:
        print("WARNING: No OAuth configs — mail delivery will fail until configured", file=sys.stderr)

    generate_cert(hostname)
    write_dovecot_users(config["smtp_username"], config["smtp_password"])
    write_main_cf(config)
    write_transport()
    ensure_aliases()
    copy_config_local(CONFIG_PATH)
    print("Configuration complete.")


if __name__ == "__main__":
    main()
